scopes:
  is_approved:
    label: Is Approved?
    type: switch
    conditions: 
      - is_approved <> 1
      - is_approved = 1
  is_public:
    label: Is Public?
    type: switch
    conditions: 
      - is_public <> 1
      - is_public = 1
  is_featured:
    label: Is Featured?
    type: switch
    conditions: 
      - is_featured <> 1
      - is_featured = 1
  category:
    label: Category
    modelClass: RedMarlin\Faq\Models\Category
    conditions: category_id in (:filtered)
    nameFrom: title